### ISSUE TITLE
I want to add Navigation bar animation

### ISSUE THREAD

**Issue by Sanchita1304** [Durgesh4993/web_Animation#10]
## Description

It is a navigation bar animation which have visual effects and transitions applied to it. It have hover effects with changing color which enhance the user experience. 
This is done by using HTML and CSS.

## Screenshot Section

![nav bar image](https://github.com/Durgesh4993/web_Animation/assets/90080911/2fd1f253-2e69-45ee-8cff-0686046a3e6b)

## Demo Video Section*

[navigation bar video.webm](https://github.com/Durgesh4993/web_Animation/assets/90080911/9a982105-f5f4-41b7-894a-a31c2efeeebe)

## Task

- [ ] Connect Us On social media -
- [ ]      <a href="https://github.com/Durgesh4993" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/in/durgesh4993/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/channel/UCRFVEkJLCknREaO40evl1uQ" target="_blank">YouTube</a>
