### ISSUE TITLE
I want to add Button Animation

### ISSUE THREAD

**Issue by Sanchita1304** [Durgesh4993/web_Animation#15]
## Description

It is a Button Animation which have hover effects and it glows as the user take the cursor in the button. It is done by using HTML and CSS.

## Screenshot Section

![button css](https://github.com/Durgesh4993/web_Animation/assets/90080911/8e2964d8-9f90-4d74-bb93-c91a8f4f64d3)
![Button html](https://github.com/Durgesh4993/web_Animation/assets/90080911/88e63ea9-282a-42fd-bcce-79658d98ad7a)

## Demo Video Section*

[button animation.webm](https://github.com/Durgesh4993/web_Animation/assets/90080911/7be5b102-a1cb-4a98-b29a-9d99e1f92efe)

## Task

- [ ] Connect Us On social media -
- [ ]      <a href="https://github.com/Durgesh4993" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/in/durgesh4993/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/channel/UCRFVEkJLCknREaO40evl1uQ" target="_blank">YouTube</a>

**Comment by Durgesh4993** [comment]
@Sanchita1304 Try to avoid, Send PR in same reposity

**Comment by Durgesh4993** [comment]
![image](https://github.com/Durgesh4993/web_Animation/assets/98798977/232d4b33-8413-4168-8e6e-5d8b3bc80750)

**Comment by Durgesh4993** [comment]
don't waste your PR

**Comment by Durgesh4993** [comment]
https://github.com/MdHRShohel/JS-OPP-DSA-Problems-Hacktoberfest2023
https://github.com/Rough4993/DataStructure

Some repos which are active, you can easily contribute.

**Comment by Sanchita1304** [comment]
Okk, Thank you
