### ISSUE TITLE
car

### ISSUE THREAD

**Issue by Durgesh4993** [Durgesh4993/web_Animation#2]
## Task

- [ ] Follow Us On social media -
- [ ]      <a href="https://github.com/Durgesh4993" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/in/durgesh4993/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/channel/UCRFVEkJLCknREaO40evl1uQ" target="_blank">YouTube</a>
