### ISSUE TITLE
Unnecessary jQuery Dependency

### ISSUE THREAD

**Issue by pradyumna14** [Durgesh4993/web_Animation#8]
## Description

The code includes a reference to jQuery for a simple background gradient animation. jQuery is a JavaScript library that provides various utility functions for DOM manipulation and simplifies cross-browser compatibility. However, in this code, jQuery is used only for a basic task, and its inclusion adds unnecessary overhead.

## Screenshot Section

![image](https://github.com/Durgesh4993/web_Animation/assets/126577744/ed516a7f-f788-4507-b17c-27999c70e7f6)

## Demo Video Section*

[screen-capture.webm](https://github.com/Durgesh4993/web_Animation/assets/126577744/50cb280f-6f2b-4a92-88ac-92916aa8fef6)

## Task

- [ ] Connect Us On social media -
- [ ]      <a href="https://github.com/Durgesh4993" target="_blank">GitHub</a>
- [ ]      <a href="https://www.linkedin.com/in/durgesh4993/" target="_blank">LinkedIn</a>
- [ ]     <a href="https://www.youtube.com/channel/UCRFVEkJLCknREaO40evl1uQ" target="_blank">YouTube</a>

**Comment by Durgesh4993** [comment]
@pradyumna14 Create a folder whose name be "amination" then add your file on that folder
